### ISSUE TITLE
Maven tests fail

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/hone-maven-plugin#27]
This problem was found in this discussion: https://github.com/objectionary/jeo-maven-plugin/issues/687

When I run `mvn clean test`, the build fails.
Steps to reporoduce: 

```
git clone git@github.com:objectionary/hone-maven-plugin.git 
cd hone-maven-plugin
mvn clean test

[ERROR] Tests run: 7, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE


find . -name "Hello.xmir"
<nothing is found>
```

**Expected output:** Tests run successfully.
**Full logs:** 
[logs.txt](https://github.com/user-attachments/files/16837982/logs.txt)
(can't attach them directly - "Comment is too long (maximum is 65536 characters)")
**Environment:**
I have the docker installed:

```
docker --version         
Docker version 20.10.11, build dea9396
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please?

**Comment by yegor256** [comment]
@volodya-lombrozo the build is clean now here in this repo

**Comment by volodya-lombrozo** [comment]
@yegor256 Yes, it works, thank you!

However, the testing time is dramatically long (but it's a separate problem):
```
[INFO] 
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:26 min
[INFO] Finished at: 2024-09-26T13:48:20+03:00
[INFO] ------------------------------------------------------------------------
```

**Comment by yegor256** [comment]
@volodya-lombrozo that's because of Docker. If you run Maven build once again, it will be much faster.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.9`
