### ISSUE TITLE
docker doesn't build the image

### ISSUE THREAD

**Issue by yegor256** [objectionary/hone-maven-plugin#32]
See https://github.com/objectionary/hone-maven-plugin/actions/runs/11065129172/job/30744022119

This is the Dockerfile: https://github.com/objectionary/hone-maven-plugin/tree/master/src/main/resources/org/eolang/hone/docker

**Comment by yegor256** [comment]
@deemp maybe you can help? It worked a week ago.

**Comment by deemp** [comment]
@yegor256, try using the [installation instructions](https://www.objectionary.com/normalizer/docs/installation.html#install-normalizer-from-hackage).

**Comment by yegor256** [comment]
@deemp thanks, fixed!
